In [1]:
m2d = [
    [1,2,3],
    [4,5,6]
]

print('Matriz pyhton 2D: ', m2d)

Matriz pyhton 2D:  [[1, 2, 3], [4, 5, 6]]


In [4]:
print(m2d[0]) #linha 0
print(m2d[1]) #linha 1

[1, 2, 3]
[4, 5, 6]


In [13]:
print(len(m2d))     #número de linhas
print(len(m2d[0]))  #número de colunas

2
3


In [7]:
print(m2d[0][0]) #linha 0 e elemento 0
print(m2d[0][1]) #linha 0 e elemento 1
print(m2d[1][1]) #linha 1 e elemento 1

1
2
5


In [3]:
m3d =   [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [255,255,255], #branco
            [255,0,0] #red
        ]
        ]

print('Matriz pyhton 3D: ', m3d)

Matriz pyhton 3D:  [[[1, 2, 3], [4, 5, 6]], [[255, 255, 255], [255, 0, 0]]]


In [9]:
print(m3d[0])        #nível 0
print(m3d[0][0])     #nível 0 linha 0
print(m3d[0][0][0])  #nível 0 linha 0 coluna 0

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1


In [10]:
print(m3d[1])        #nível 1
print(m3d[1][1])     #nível 1 linha 1
print(m3d[1][1][0])  #nível 1 linha 1 coluna 0

[[255, 255, 255], [255, 0, 0]]
[255, 0, 0]
255


In [18]:
print(len(m3d))        #número de níveis
print(len(m3d[0]))     #número de linhas
print(len(m3d[0][0]))  #número de colunas

print('Tamanho da Matriz: ', len(m3d) * len(m3d[0]) *len(m3d[0][0]))  

2
2
3
Tamanho da Matriz:  12


#### Comparação Array Python x NumPy

In [21]:
#testa lista pyhton
import time
lista = list(range(1000000)) # 1 milhão
ini =time.time()

for _ in range(100):
    lista = [x * 2 for x in lista]
    
fim = time.time()
dif1 = fim - ini
print('Tempo array python: ', dif1)


Tempo array python:  34.19431710243225


In [23]:
#testa array numpy
import numpy as np
arr = np.arange(1000000)
ini = time.time()

for _ in range(100):
    arr *= 2

fim = time.time()
dif1 = fim - ini
print('Tempo array numpy: ', dif1)

Tempo array numpy:  0.18963909149169922


### Array numpy 2D a partir de uma lista

In [25]:
#axis = 0 -> significa coluna
#axis = 1 -> significa linha

import numpy as np
lista = [
    [1,2,3],
    [4,5,6]
]

matriz = np.array(lista)
print(matriz)
display(matriz)

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
#propriedades do array numpy
print('Número de dimensões:', matriz.ndim) #2D
print('Tipo de Objeto:', type(matriz)) #numpy.ndarray
print('Tipo de dado numpy:', matriz.dtype) #data type = int 32 bits
print('Tamanho do Array:', matriz.size) #quantidade de itens na matriz
print('Formato do Array:', matriz.shape) #dimensões 2x3
print('Nº de Linhas:', matriz.shape[0])
print('Nº de Colunas:', matriz.shape[1])

Número de dimensões: 2
Tipo de Objeto: <class 'numpy.ndarray'>
Tipo de dado numpy: int32
Tamanho do Array: 6
Formato do Array: (2, 3)
Nº de Linhas: 2
Nº de Colunas: 3


In [39]:
#Métodos ou funções do array numpy
print('Mínimo:', matriz.min())
print('Máximo:', matriz.max())
print('Média:', matriz.mean())
print('Soma:', matriz.sum())
print('Desvio Padrão:', matriz.std())
print('Desvio Padrão (coluna):', matriz.std(axis=0))
print('Desvio Padrão (linha):', matriz.std(axis=1))
print('')
#quando usa eixo, a coluna vem antes da linha... ou seja, coluna e linha
# geralmente é linha e coluna em uma matriz.
print('Mínimo (coluna):', matriz.min(axis=0))
print('Mínimo (linha):', matriz.min(axis=1))
print('')
print('Máximo (coluna):', matriz.max(axis=0))
print('Máximo (linha):', matriz.max(axis=1))

Mínimo: 1
Máximo: 6
Média: 3.5
Soma: 21
Desvio Padrão: 1.707825127659933
Desvio Padrão (coluna): [1.5 1.5 1.5]
Desvio Padrão (linha): [0.81649658 0.81649658]

Mínimo (coluna): [1 2 3]
Mínimo (linha): [1 4]

Máximo (coluna): [4 5 6]
Máximo (linha): [3 6]


In [43]:
lista = [
    [3,2,1],
    [6,5,4],
    [1,7,2]
]

a = np.array(lista)

In [46]:
#Fatiamento (seleção com intervalos)
display(a[0][:2]) 

array([3, 2])

In [49]:
#Seleção
print(a[0][0:2]) #linha 0 e colunas 0 e 1
#OU
print(a[0, 0:2])



[3 2]
[3 2]
