In [15]:
import numpy as np
import pandas as pd


km = np.loadtxt(fname='carros-km.txt')
#print(km)
print('Tipo de Dado: ',km.dtype)
print('Dimensões: ',km.ndim)
print('Formato: ',km.shape)
print('Quantidade de itens: ',km.size)
print('Minimo: ', km.min())
print('Máximo: ', km.max())
print(f'Média:  {km.mean():.2f}')
print(km[:9]) #9 primeiros números
print(km[-9:]) #9 últimos números

Tipo de Dado:  float64
Dimensões:  1
Formato:  (258,)
Quantidade de itens:  258
Minimo:  0.0
Máximo:  119945.0
Média:  44499.41
[44410.  5712. 37123.     0. 25757. 10728.     0. 77599. 99197.]
[89685. 85384. 98108. 71280. 27505. 29981. 52637.  7685. 50188.]


#### Lista => Array NumPy => DF pandas

In [17]:
lista = [
    ['laranja', 'computador', 'segunda'],
    ['banana', 'teclado', 'quarta'],
    ['uva', 'mouse', 'sexta']
]


#cria um df pandas a partir da lista 2d

df = pd.DataFrame(lista, columns=['Frutas', 'Eletrônicos', 'Dias'])
display(df)

Frutas Eletrônicos     Dias
0  laranja  computador  segunda
1   banana     teclado   quarta
2      uva       mouse    sexta

In [18]:
#cria um df a partir de um array numpy
a = np.array(lista)
df = pd.DataFrame(a, columns=['Frutas', 'Eletrônicos', 'Dias'])
display(df)

Frutas Eletrônicos     Dias
0  laranja  computador  segunda
1   banana     teclado   quarta
2      uva       mouse    sexta

In [22]:
#cria uma lista a partir de uma lista de 1D ( 1 Dimensão )
a = np.array([10,200,30,40])

df = pd.DataFrame(a, columns=['Valores'])
display(df)

Valores
0       10
1      200
2       30
3       40

In [26]:
a = np.array([1,2,3,4,5,4,4])
display(a)


#buscar os valores que são iguais a 4
np.where(a == 4)

array([1, 2, 3, 4, 5, 4, 4])

(array([3, 5, 6], dtype=int64),)