## numpy.org
#### Principal biblioteca de programação científica.
#### Arrays numpy são 50x mais rápidos de processar do que uma lista.
#### Porém enquanto listas aceitam vários tipos de dados, um array numpy precisa ser de um único tipo.

In [1]:
#array pyhton - é uma lista
arr = [0,1,2,3,4,5,6] #uma dimensão
type(arr)

list

In [2]:
#mais fácil
arr = list(range(10))
print(arr)
type(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [3]:
import numpy as np

print('PI', np.pi)

#array numpy
arr = np.arange(10)
print(arr)

PI 3.141592653589793
[0 1 2 3 4 5 6 7 8 9]


In [4]:
#importa somente a função arange
from numpy import arange
print(arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#array numpy a partir de uma lista
arr = np.array([100, 200, 300, 400])
print(arr)


#array numpy a partir de uma tupla
arr2 = np.array((120, 340, 500, 100))
print(arr2)

[100 200 300 400]
[120 340 500 100]


In [6]:
#indexação
print(arr[0])
print(arr[2])
print(arr[1])

100
300
200


In [7]:
arr = np.array([100, 200, 300, 400, 500, 600, 700])
#seleção
print(arr[0:3])
print(arr[2:])
print(arr[:4])
print(arr[2:4])
print(arr[-1])

[100 200 300]
[300 400 500 600 700]
[100 200 300 400]
[300 400]
700


In [8]:
#fatiamento
#é a selação mas você não quer pegar continuo

print(arr[0:5:2])
print(arr[0::2])

[100 300 500]
[100 300 500 700]


DIA 26/11/2022

In [9]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.random.random((3,2))

array([[0.13345294, 0.75157709],
       [0.96482229, 0.72150063],
       [0.8806394 , 0.96137096]])

In [11]:
np.random.randint((3,2))

array([0, 1])

In [12]:
#não é uma matriz
#gera 5 números entre 1 e 9

np.random.randint(1,10,5)

array([9, 6, 5, 5, 1])

In [13]:
a = np.random.randint(1,10,(3,2))
print(a)

[[4 6]
 [5 9]
 [9 1]]


In [14]:
a = np.random.randint(1,10,(2,3,2))
print(a)

[[[3 7]
  [5 2]
  [9 6]]

 [[5 7]
  [8 2]
  [7 7]]]


In [15]:
np.random.shuffle(a)
print(a)

[[[5 7]
  [8 2]
  [7 7]]

 [[3 7]
  [5 2]
  [9 6]]]


In [17]:
a = np.array([-9,-3,7,2,-8,4])
b = np.array([10]) 
c = a + b
print(c)
d = a - b
print(d)

[ 1  7 17 12  2 14]
[-19 -13  -3  -8 -18  -6]


## Operações básicas sobre arrays

In [18]:
a = np.arange(9)
print(a)
b = a.reshape((3,3))
print(b)

#soma todos os elementos
print('\nSoma:', b.sum())

#soma colunas
print('Soma colunas:', b.sum(axis=0))

#soma linhas
print('Soma linhas:', b.sum(axis=1))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Soma: 36
Soma colunas: [ 9 12 15]
Soma linhas: [ 3 12 21]


# Operações com matrizes

In [19]:
#vetoriza
dados = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
])

np.max(dados, axis=0)
np.max(dados, axis=1)

array([3, 6, 9])

# Fatiamento

In [20]:
a = np.array([0,1,2,3,4,5])

In [21]:
print(a[0:5:2])

[0 2 4]


In [22]:
#fatiamento para atribuição
b = a[2:5]
print(b)
b[:] = 9
print(b)      

[2 3 4]
[9 9 9]


In [23]:
a = np.arange(20)
print(a)
a[5:10] = 0
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  0  0  0  0  0 10 11 12 13 14 15 16 17 18 19]
